language: node_js
node_js:
  - "8"
install:
  - npm install esm
  - npm install -g codecov standard tape tap-spec nyc
branches:
  only:
  - master
  - development
script:
  - npm run lint
  - npm run test:cov
  - npm run check-cov
after_success: npm run report
