# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.3
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.5

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/kyanite

    steps:
      - checkout

      - run:
          name: install-deps
          command: npm ci

      # lint
      - run:
          name: lint
          command: npm run lint
      # run tests and report coverage
      - run:
          name: test
          command: npm run test:cov
      # generate coverage report
      - run:
          name: generate-report
          command: npm run report
      # send to codecov
      - codecov/upload:
          upload_name: k-tests
          token: $CODECOV_TOKEN
          file: coverage.lcov
          flags: unittests
      # run coverage check
      - run:
          name: coverage
          command: npm run check-cov
  docs:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.5
    working_directory: ~/kyanite
    steps:
      - checkout

      #Install deps
      - run:
          name: Install Dependencies
          command: npm ci

      # Build docs
      - run:
          name: Build docs
          command: npm run docs

      - persist_to_workspace:
          root: .
          paths:
            - docs/*
  docs-deploy:
    docker:
      - image: circleci/node:10.5
    working_directory: ~/kyanite
    steps:
      - checkout
      - attach_workspace:
          at: ~/kyanite
      - add_ssh_keys:
          fingerprints:
            - "05:16:6f:2d:1d:63:40:9a:42:f2:e8:8f:90:22:da:15"
      - run:
          name: Install gh-pages and Configure
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@dusty.codes"
            git config user.name "ci-build"
      - run:
          name: Deploy Docs
          command: gh-pages --dist ~/kyanite/docs
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - development
  deploy_docs:
    jobs:
      - docs
      - docs-deploy:
          requires:
            - docs
          filters:
            branches:
              only: development
